uv run /fs/nexus-scratch/ltahboub/CoupledSceneSampling/SEVA/demo.py \
    --data_path "/fs/nexus-scratch/ltahboub/CoupledSceneSampling/test_datapath" \
    --task img2trajvid_s-prob \
    --replace_or_include_input True \
    --traj_prior circle \
    --cfg 4.0,2.0 \
    --guider 1,2 \
    --num_targets 111 \
    --L_short 576 \
    --use_traj_prior True \
    --chunk_strategy interp
